### ISSUE TITLE
Get this auto-updated using a cron job on Travis CI

### ISSUE THREAD

**Issue by domenic** [w3c/mdn-spec-links#1]
Seems like the logical next step :). @foolip has some expertise here.

**Comment by foolip** [comment]
@sideshowbarker would it suffice to just run the `make` on Travis daily and deploy the results to a branch? You could do a branch in the same repo, or use a similar setup to reffy/reffy-reports.

Here's the style of deploy in Travis that I've found most readable:
https://github.com/w3c/speech-api/blob/master/.travis.yml

**Comment by sideshowbarker** [comment]
Update:

1. The mdn-spec-links build is now automatically triggered each time a change is merged to BCD, and each time a change is merged to MDN.
2. If when running the mdn-spec-links build any errors are encountered (e.g., spec URLs with bad fragment IDs), the automation sets the build status for the repo to `failure` — so that a red ❌ will shows up in the expected place at the top of the https://github.com/w3c/mdn-spec-links/ page.
3. If no build errors are encountered, the automation creates a new PR with the changes resulting from running the build.

https://github.com/w3c/mdn-spec-links/blob/main/.github/workflows/build.yml is the workflow file that runs those steps.
