### ISSUE TITLE
Schema or TypeScript declaration for data

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/mdn-spec-links#3]
It was a bit difficult to figure out from code and data files what all fields are there, so I created this TypeScript declaration:

``` ts
interface MdnData {
  [id: string]: MdnEntry[];
}

interface MdnEntry {
  engines: string[];
  filename: string;
  name: string;
  slug: string;
  summary: string;
  support: {
    [browser: string]: {
      version_added: string | boolean | null;
      version_removed?: string;
      notes?: string;
    };
  };
  title: string;
}
```

I also generated a JSON schema at https://app.quicktype.io?share=5792So9xCL3hM0e2XhUo.

Maybe we can add this to wiki or docs?

Question:
- Why is the following an array? Are there any instances where it has a length more than 1?
https://github.com/w3c/mdn-spec-links/blob/0f0d35f0c2f99e4b24075ebf4c2f296ba487a747/appmanifest.json#L2-L3
- Did I miss anything in the declaration?

**Comment by sideshowbarker** [comment]
> It was a bit difficult to figure out from code and data files what all fields are there, so I created this TypeScript declaration:

Thanks — that inspired me to raise #4. If you could review it that would be great.

> I also generated a JSON schema at https://app.quicktype.io?share=5792So9xCL3hM0e2XhUo.

#4 also adds a JSON schema (generated with https://github.com/vega/ts-json-schema-generator).

> Maybe we can add this to wiki or docs?

#4 includes an update to the README.md

> Question:
> 
> * Why is the following an array? Are there any instances where it has a length more than 1?
>   https://github.com/w3c/mdn-spec-links/blob/0f0d35f0c2f99e4b24075ebf4c2f296ba487a747/appmanifest.json#L2-L3

Yes there are quite a lot of instances where it has a length more than 1. The reason is that there are many cases where multiple MDN articles cite the same fragment ID in a particular spec. So, because the spec fragment IDs are the keys for top-level entries, each spec fragment ID may be associated with multiple BCD/MDN features.

> * Did I miss anything in the declaration?

Yes 😁 — the data is a bit complex; see #4 for the details

**Comment by sideshowbarker** [comment]
@sidvishnoi Thanks extremely much for having taken time to raise this issue. Until you did, I had no idea it was possible to use TypeScript to express JSON data structure/constraints — and to then generate a JSON Schema from the TypeScript source.

JSON Schema and the associated tooling around it seem like a really good way to deal with JSON validation — but I find it a bit painful to using JSON Schema as an authoring format. So after you raised this issue, it was really an eye-opener for me to see how the constraints could be expressed in TypeScript with a much more compact, authoring-friendly syntax.

And to me at least, the combination of the compact syntax support for support for embedding comments obviates the need to write up separate documentation about the data format — because the TypeScript source can be self-documenting, serving very neatly both as a formalism for defining the data format, as well as the documentation for it.

So thanks again — this has been a very-welcome and much-appreciated learning experience for me.

**Comment by sidvishnoi** [comment]
Thank you for such kind words. I'm happy I was helpful :slightly_smiling_face:
