### ISSUE TITLE
Fetch specifications data from SpecData.json

### ISSUE THREAD

**Issue by SebastianZ** [w3c/mdn-spec-links#5]
The specifications used in the *Specifications* sections of the MDN articles use the data from https://github.com/mdn/kumascript/blob/master/macros/SpecData.json.

Maybe the data to generate the specification links could also be fetched from there? Or the specs could be added directly to the features in the browser-compat-data. I saw you've already done that for the JS features in https://github.com/mdn/browser-compat-data/pull/2983, @sideshowbarker.

Sebastian

**Comment by sideshowbarker** [comment]
Hi Sebastin, Thanks for raising this

> The specifications used in the _Specifications_ sections of the MDN articles use the data from https://github.com/mdn/kumascript/blob/master/macros/SpecData.json.

Yes — specifically, MDN gets the specification titles and base URLs from there, along with the spec status (Working Draft, Candidate Recommendation, etc.)

But for the purposes of this mdn-spec-links repo, we don’t need the titles nor the status. We do need the spec URLS, but those URLs need to also have fragments, with fragment IDs for particular parts of the specs. The SpecData.json file doesn’t provide those URLs. Instead those are only available within individual MDN articles.

> Maybe the data to generate the specification links could also be fetched from there?

For the reasons outlined above, the mdn-spec-links repo doesn’t have direct use for data from that SpecData.json file.

> Or the specs could be added directly to the features in the browser-compat-data.

That’s the long-term plan. I personally would prefer we just go ahead and do that — but so far, I’ve not be able to get agreement for others involved with BCD to do that.

> I saw you've already done that for the JS features in [mdn/browser-compat-data#2983](https://github.com/mdn/browser-compat-data/pull/2983)

Yes — that’s because we did get specific agreement to add the spec URLs for the JS features. And it’s worked out well — so I hope we can get agreement for the rest too, before too long.

**Comment by SebastianZ** [comment]
> But for the purposes of this mdn-spec-links repo, we don’t need the titles nor the status. We do need the spec URLS, but those URLs need to also have fragments, with fragment IDs for particular parts of the specs. The SpecData.json file doesn’t provide those URLs. Instead those are only available within individual MDN articles.

Ah, right, the fragment IDs for the different features are the important thing here. Yes, that info is only available from within the articles at the moment, as far as I know.

> > Or the specs could be added directly to the features in the browser-compat-data.
> 
> That’s the long-term plan. I personally would prefer we just go ahead and do that — but so far, I’ve not be able to get agreement for others involved with BCD to do that.
> 
> > I saw you've already done that for the JS features in [mdn/browser-compat-data#2983](https://github.com/mdn/browser-compat-data/pull/2983)
> 
> Yes — that’s because we did get specific agreement to add the spec URLs for the JS features. And it’s worked out well — so I hope we can get agreement for the rest too, before too long.

The discussion in https://github.com/mdn/browser-compat-data/issues/1531 sounds like people are positive about adding spec. links everywhere, but given that [almost the whole MDN content staff got unemployed last month](https://blog.mozilla.org/blog/2020/08/11/changing-world-changing-mozilla/), I fear those changes won't happen anytime soon. 😞

Sebastian

**Comment by sideshowbarker** [comment]
> The discussion in [mdn/browser-compat-data#1531](https://github.com/mdn/browser-compat-data/issues/1531) sounds like people are positive about adding spec. links everywhere, but given that [almost the whole MDN content staff got unemployed last month](https://blog.mozilla.org/blog/2020/08/11/changing-world-changing-mozilla/), I fear those changes won't happen anytime soon. 😞

Yeah, I think certainly those changes aren’t going to happen at least until Florian is back working on MDN again. At least I myself wouldn’t agree to them happening unless Florian is around to review and explicitly OK it.

**Comment by sideshowbarker** [comment]
@Elchi3 has since built and deployed a robust way to get the necessary spec data. So I’m going ahead and closing this as resolved. But if there’s still anything missing, we can revisit this.
