### ISSUE TITLE
css-contain missing

### ISSUE THREAD

**Issue by SebastianZ** [w3c/mdn-spec-links#6]
The list is currently missing the spec. link for [CSS Contain 1](https://drafts.csswg.org/css-contain-1/) causing Bikeshed to spit out a fatal error.

Sebastian

**Comment by sideshowbarker** [comment]
> The list is currently missing the spec. link for [CSS Contain 1](https://drafts.csswg.org/css-contain-1/) causing Bikeshed to spit out a fatal error.

As far I as I know, given the way the mdn-spec-links data is collected, the only reason the CSS Contain 1 spec would be missing is if there are no MDN articles with Specifications tables that reference URLs from the CSS Contain 1 spec.

And as far as the Bikeshed error being fatal, I think the way to avoid that is to not set **Include MDN Panels** to `yes`, `on`, or  `true`, but instead set it to a so-called “soft-boolish” value: https://tabatkins.github.io/bikeshed/#soft-boolish — that is, either `maybe`, `if possible`, or `if needed`.

**Comment by SebastianZ** [comment]
> As far I as I know, given the way the mdn-spec-links data is collected, the only reason the CSS Contain 1 spec would be missing is if there are no MDN articles with Specifications tables that reference URLs from the CSS Contain 1 spec.

I already checked for that and there is at least https://developer.mozilla.org/en-US/docs/Web/CSS/contain, which has a [specifications table referring to it](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/contain?raw&macros&section=Specifications). Interestingly, CSS Contain 2 _is_ included in the list while there is no MDN page for the [`content-visibility` property](https://drafts.csswg.org/css-contain-2/#content-visibility) defined in it yet.

> And as far as the Bikeshed error being fatal, I think the way to avoid that is to not set **Include MDN Panels** to `yes`, `on`, or `true`, but instead set it to a so-called “soft-boolish” value: https://tabatkins.github.io/bikeshed/#soft-boolish — that is, either `maybe`, `if possible`, or `if needed`.

Good to know! Let's see if I can come up with a patch for that. Thank you for the info!

Sebastian

**Comment by sideshowbarker** [comment]
> I already checked for that and there is at least https://developer.mozilla.org/en-US/docs/Web/CSS/contain, which has a [specifications table referring to it](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/contain?raw&macros&section=Specifications).

I see that Specifications table links to https://drafts.csswg.org/css-contain/, which is CSS Containment Module Level 2, right?

I realize in https://developer.mozilla.org/en-US/docs/Web/CSS/contain#Specifications the rendered hypertext of the link says *CSS Containment Module Level 1*; but https://github.com/mdn/kumascript/blob/master/macros/SpecData.json#L467 is the cause of that problem — in that it has the wrong title for the spec at https://drafts.csswg.org/css-contain/. The spec currently at that URL is the Level 2 spec, not the Level 1 spec. There are a number of such cases where the SpecData.json has mismatches like that — I have submitted quite a few patches/PRs to fix them, when I find them.

**Comment by SebastianZ** [comment]
Oh, you're right! I have [created a pull request to fix the URL and to add the level 2 spec. URL now](https://github.com/mdn/kumascript/pull/1422).

Thank you for the hint!

Sebastian

**Comment by SebastianZ** [comment]
Meanwhile the patch already got merged and I also updated the MDN page right now to include both, level 1 and level 2 of the spec.

How often does the scraping happen?

Sebastian

**Comment by sideshowbarker** [comment]
> Meanwhile the patch already got merged and I also updated the MDN page right now to include both, level 1 and level 2 of the spec.

OK, thanks — I’ve run an update, so now those changes should have been picked up. If not, lemme know.

> How often does the scraping happen?

There’s so far not been any set schedule at which it happens. I’ve just run it manually. But I suppose it’d be better if I ran it every day, so that’s what I’ll do from now on.

**Comment by SebastianZ** [comment]
> > Meanwhile the patch already got merged and I also updated the MDN page right now to include both, level 1 and level 2 of the spec.
> 
> OK, thanks — I’ve run an update, so now those changes should have been picked up. If not, lemme know.

Uhm, no, because [you removed the Level 1 spec. again](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/contain$compare?locale=en-US&to=1647320&from=1647123). 😄 What was the reason for that?

> > How often does the scraping happen?
> 
> There’s so far not been any set schedule at which it happens. I’ve just run it manually. But I suppose it’d be better if I ran it every day, so that’s what I’ll do from now on.

👍 

Sebastian

**Comment by sideshowbarker** [comment]
> Uhm, no, because [you removed the Level 1 spec. again](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/contain$compare?locale=en-US&to=1647320&from=1647123). 😄 What was the reason for that?

Ah, sorry — when I did that MDN edit, I hadn’t made the connection that it was related in any way to this.

The Level 1 spec doesn’t seem to be separately referenced in any other MDN articles. And because of that, when mdn-spec-links does its scraping, the `css-contain-1.json` file is generates contains data for only that one anchor. That seems to be a very limited usefulness.

For the Specifications table in MDN. understanding is that in general these days, we’ve been avoiding to list multiple versions of spec when there’s one version that’s sufficient. Certainly that’s the case for the JavaScript articles, where the policy is to only cite the latest ES draft.

In the specific case of the `contain` property, it’s included in Level 2 spec, and the definition for it there effectively obsoletes the definition in the Level 1 spec. So it’s not clear to me what value there is to web developers to have it in also citing the Level 1 spec in the MDN article.

But in addition to that, as far as mdn-spec-links goes, processing that spec citation would result in the Level 1 spec having exactly just one MDN spec annotation in it. On the face of it, that doesn’t seem super useful to anybody in practice.

All that said, if you feel strongly that it should be included in mdn-spec-links, then we can add it. Lemme know.

**Comment by sideshowbarker** [comment]
We have only one `css-contain.json` data file, and that’s very much by design. If that is currently causing problems somewhere downstream, we can revisit this.
