### ISSUE TITLE
IndexedDB missing MDN panels for IDBKeyRange/lowerBound and IDBKeyRange/upperBound

### ISSUE THREAD

**Issue by inexorabletash** [w3c/mdn-spec-links#7]
@sideshowbarker  - I bet you can help here...

dfns here, which seem fine:

* https://github.com/w3c/IndexedDB/blob/main/index.bs#L4150
* https://github.com/w3c/IndexedDB/blob/main/index.bs#L4165
* https://github.com/w3c/IndexedDB/blob/main/index.bs#L4182
* https://github.com/w3c/IndexedDB/blob/main/index.bs#L4198

All of these MDN pages exist:

* https://developer.mozilla.org/en-US/docs/Web/API/IDBKeyRange/only
* https://developer.mozilla.org/en-US/docs/Web/API/IDBKeyRange/upperBound
* https://developer.mozilla.org/en-US/docs/Web/API/IDBKeyRange/lowerBound
* https://developer.mozilla.org/en-US/docs/Web/API/IDBKeyRange/bound

I suspect the fault lies in:

https://w3c.github.io/mdn-spec-links/indexeddb-3.json 

which has keys for:

*    "dom-idbkeyrange-only"
*    "dom-idbkeyrange-lowerbound-lower-open-lower"
*    "dom-idbkeyrange-upperbound-upper-open-upper"
*    "dom-idbkeyrange-bound"

Note how some of those have extra stuff (arguments), which correspond to the missing MDN panels - is this something in MDN that's causing the JSON generation to go wonky? Or something in the tooling here?

**Comment by sideshowbarker** [comment]
Hi Joshua — thanks for taking time to raise this.

So this is actually a general known problem, but it’s a usability bug rather than a tooling bug; that’s because the annotations are actually there — but just not aligned in the place at point of use where a normal user would be expect to find them.

To show what I mean: Go to https://w3c.github.io/IndexedDB/#keyrange and notice there are two MDN annotations around there; the firs aligns with the **The IDBKeyRange interface**, and the second aligns with the top of the IDL block:

<img width="917" alt="Screen Shot 2020-11-21 at 9 52 10" src="https://user-images.githubusercontent.com/194984/99862986-62c96800-2bdf-11eb-8978-c9274c13d6d6.png">

If you expand that second annotation, you’ll see this:

<img width="919" alt="Screen Shot 2020-11-21 at 9 59 41" src="https://user-images.githubusercontent.com/194984/99863184-5396ea00-2be0-11eb-9d9e-37250828410e.png">

…so that’s where the two annotations you were looking for are hiding/buried.

The by-design behavior is all that all the MDN annotations for any dfn’ed members of an IDL definition get squashed into a single annotation a the top of the IDL block.

I’m unhappy I ended up needing to design the behavior that way, but it’s an unfortunate result of the fact that if we instead have the tooling align each annotation at point of use with the actual specific member the annotations corresponds to, it has some undesirable consequences.

One specific problem I ran into with doing it that way was that breaks the expected copy-paste behavior when somebody tries to copy the IDL block — because it causes the contents of the annotations to get copied onto the clipboard along with the actual IDL content.

One other specific problem I ran into was that it causes the markup of the IDL content to be invalid/non-conforming, so any documents which had it that way would fail to pass pubrules, etc.

It’s actually a pretty hard problem to really fix — but I feel that the bad usability of the current behavior requires at least coming up with some workaround. And so far the only practical workaround I’ve managed to think of is to make an exception to the default show/hide behavior of the MDN annotations for the IDL blocks such that unlike the annotations for other spec parts, the annotations for the IDL blocks are shown expanded by default, rather than collapsed.

So please lemme know what you think of that idea.

Showing the MDN annotations for IDL blocks expanded by default also isn’t ideal for usability — but it seems to me it’s at least slightly better for usability than the behavior as it stands now, with the annotations getting hidden/buried, and users missing the fact they’re even there.

If it seems like a good idea to change the behavior to make the IDL annotations expanded by default, then I suppose I could add a Bikeshed option to allow editors to override it if they wanted.

**Comment by sideshowbarker** [comment]
Now that I’ve said all the stuff in my previous comment, I realize there’s a completely different solution I want to suggest and that I think is much better solution; and that’s this:

_Never link to member definitions in IDL blocks from MDN articles to begin with._

To address the concrete case of the specific links in the issue description here, I think the MDN articles should rightly link to https://w3c.github.io/IndexedDB/#dom-idbkeyrange-lowerbound and to https://w3c.github.io/IndexedDB/#dom-idbkeyrange-upperbound — in the body of the spec — rather than to those dfn’s inside the IDL block.

Do you agree?

If we were to have agreement about that as a general best practice — I mean, agreement that for IDL-defined members, MDN articles should link to the anchors in the spec body where the requirements for those members are actually specified, rather than to where those members are referenced in the IDL blocks — than it’s possible that:

1. In Bikeshed could add some linting to report warnings for the cases where MDN annotations are getting squashed into the top of an IDL block. Adding that check would be simple, relatively very low LOE.
2. In my upstream mdn-spec-links tool, I could add some preemptive linting to identify cases where we find MDN articles that are linking into IDL blocks. But adding that check would not be simple, and would require a relatively LOE.

So maybe for now, I could start by adding <span>#</span>1, and then plan to make time later to work on putting something for <span>#</span>2 together.

**Comment by inexorabletash** [comment]
SGTM

**Comment by sideshowbarker** [comment]
> SGTM

OK, cool — I’ll get one or more Bikeshed PRs put together sometime soon for the Bikeshed changes I mentioned:

* add some linting to report warnings for the cases where MDN annos are getting squashed into the top of an IDL block
* change Bikeshed to make an exception to the default show/hide behavior of MDN annos for IDL blocks such that unlike annos for other spec parts, the ones for IDL blocks are shown expanded by default, not collapsed (+ add a new Bikeshed option to allow overriding that)

**Comment by inexorabletash** [comment]
I guess I'm still confused why two of the four cited methods appear near the IDL whereas the other two appear near the prose definitions. I'm not sure what Bikeshed linting would reveal, but diagnostics can't hurt!

I'm skimming this thread on a phone so the problem is likely my inability to focus properly at the moment.

**Comment by sideshowbarker** [comment]
> I guess I'm still confused why two of the four cited methods appear near the IDL whereas the other two appear near the prose definitions.

That’s simply because whoever added the spec links to those two articles chose for whatever reason to use the anchors inside the IDL — whereas whoever added the other two chose to use the anchors near the prose definitions.

In other words, the tooling isn’t programmatically selecting link targets to use; instead the link targets are input data scraped from MDN articles, and so that data is the result of somewhat arbitrary and possibly inconsistent choices that one or more people made in the process of creating or updating the MDN articles from which the data is scraped.

**Comment by inexorabletash** [comment]
Got it. So the diagnostics would tell the spec author that it isn't their fault, and hopefully indicate a fix is needed on MDN itself.

**Comment by sideshowbarker** [comment]
> So the diagnostics would tell the spec author that it isn't their fault, and hopefully indicate a content fix is needed on MDN itself.

Right — but I can make the warning message include the URL for the actual MDN article that’s the source of the problem link, so a spec editor seeing the warning can know exactly which article needs to be edited.

**Comment by inexorabletash** [comment]
BTW, is there any benefit to leaving the two MDN pages alone until you tackle this, as a repro case? Or should I go ahead and fix their links now?

**Comment by sideshowbarker** [comment]
> BTW, is there any benefit to leaving the two MDN pages alone until you tackle this, as a repro case? Or should I go ahead and fix their links now?

Please feel free to go ahead and fix the links now. There’s no benefit to leaving the pages alone — because I’ve since written a check that basically goes through every single one of our current specs, to find instances where there’s a defined term that’s inside an IDL block is linked to, and I found about 150 of them…

In other words, I’ve got a sufficient number of repro cases at this point  — so I’d even be happy for there be a couple less :)

**Comment by inexorabletash** [comment]
Added fun - the anchors changed between v1, v2 (current TR) and v3 (ED) of the spec. The MDN pages hadn't been re-run since V2 was ED, though... Anyway, for two pages I added v3 links, made v2 explicit rather than implicit, fixed those links, and hopefully the v3 will get picked up correctly when tooling runs and I next poke the spec.

**Comment by inexorabletash** [comment]
Also... what triggers a regeneration of the data here? i.e. if I've tweaked MDN, is there a scheduled process that should consume the updates?

**Comment by sideshowbarker** [comment]
> Also... what triggers a regeneration of the data here? i.e. if I've tweaked MDN, is there a scheduled process that should consume the updates?

Currently nothing automatically triggers regeneration of the data; instead I run a script to regenerate it — typically once a week, at the end of the week.

So I’ll run the script by the end of this week, which means the generated data will be up to date at the beginning of next week.

The reason it’s not fully automated is that the process sometimes involves manually fixing some merge conflicts, and also because some error reporting I have built into the script usually surfaces a few places where ensuring the generated data is accurate requires me to stop and make upstream changes to MDN (e.g., to fix spec URLs/fragments) or browser-compat-data.

And the reason it’s behind on being updated right now is that my partner and I just had a new baby born on November 25, so my availability has been extremely limited for the last two weeks — and will remain a bit limited til the end of the year a least — but this week I’ve been whittling away at my backlog as time allows. (And making mdn-spec-links a priority, because we have a lot of specs relying on it now.)

**Comment by inexorabletash** [comment]
> my partner and I just had a new baby born on November 25

Congrats! 🎉🎉🎉🎉

**Comment by inexorabletash** [comment]
This has been resolved. Thanks!

**Comment by sideshowbarker** [comment]
Cheers — now this repo has only two open issues 😀
